benchmarks:
- freetype2-2017
- bloaty_fuzz_target
description: null
docker_registry: gcr.io/fuzzbench
experiment: aakash-new-commit123
experiment_filestore: /tmp/experiment-data
fuzzers:
- neuzz
- afl
- libfuzzer
git_hash: db192b60815ac87f69ee0f7f3e37aeac71949e1b
local_experiment: true
max_total_time: 5000
no_dictionaries: false
no_seeds: false
oss_fuzz_corpus: false
report_filestore: /tmp/report-data
trials: 3
